"""Реестр моделей данных.

Импорт модулей моделей здесь обеспечивает регистрацию таблиц в
`Base.metadata` (используется Alembic для миграций). Модели добавляются
задачами блока 1.B по мере реализации.
"""

from app.db.base import Base
from app.models.organization import (
    Department,
    Employee,
    Organization,
    Position,
)
from app.models.access_grant import ProjectAccess
from app.models.agent import AgentProposal, AgentRun, AIAgent
from app.models.audit import AuditEvent
from app.models.content import (
    DailyReport,
    DailyReportWorkItem,
    Document,
    DocumentVersion,
    File,
    Notification,
)
from app.models.estimate import (
    CommercialOffer,
    Estimate,
    EstimateChange,
    EstimatePosition,
    PricingSettings,
    RateItem,
    UnitOfMeasure,
)
from app.models.procurement import (
    GoodsReceipt,
    GoodsReceiptLine,
    InventoryBalance,
    InventoryCount,
    InventoryCountLine,
    InventoryTransaction,
    MaterialIssue,
    MaterialIssueLine,
    MaterialRequest,
    MaterialRequestLine,
    MaterialReturn,
    ProcurementSettings,
    PurchaseOrder,
    PurchaseOrderLine,
    QuoteComparison,
    RequestForQuotation,
    RfqLine,
    RfqSupplier,
    StockReservation,
    StockTransfer,
    SupplierItemOffer,
    Warehouse,
    WarehouseLocation,
    WriteOffDocument,
)
from app.models.project import (
    Project,
    ProjectDiscipline,
    ProjectLocation,
    ProjectMember,
    ProjectMilestone,
    Site,
)
from app.models.design import (
    Counterparty,
    DesignBrief,
    DesignConcept,
    DesignIssue,
    DesignSpecification,
    MarketAvailabilityCheck,
    Material,
    Supplier,
    SupplierProduct,
)
from app.models.crm import (
    Communication,
    Contract,
    CounterpartyContact,
    CrmSettings,
    Deal,
    DealLossReason,
    DealStageHistory,
    Lead,
    LeadSource,
    PipelineStage,
    SalesTarget,
)
from app.models.finance import (
    Budget,
    BudgetLine,
    ExpenseCategory,
    FinanceSettings,
    FinancialCommitment,
    Invoice,
    Payment,
    PaymentRequest,
)
from app.models.accountable import (
    AccountableAdvance,
    AccountableExpense,
    AdvanceReport,
    AdvanceSettlement,
    ExpenseDocument,
)
from app.models.personnel import (
    DailyReportHeadcount,
    DailyReportIssue,
    ForemanJournal,
    PayrollDraft,
    PayrollLine,
    SafetyClearance,
    SiteWorkerAssignment,
    WorkPermit,
    WorkShift,
)
from app.models.equipment import (
    Equipment,
    EquipmentAssignment,
    EquipmentInspection,
    EquipmentUsageLog,
    FuelTransaction,
    MaintenanceOrder,
    Tool,
    ToolAssignment,
)
from app.models.field_report import DailyReportEquipment, DailyReportFile
from app.models.inbox import InboxItem
from app.models.audit_finding import AuditFinding
from app.models.integration import IntegrationConnector, OutboundMessage
from app.models.smm import (
    ContentPlanItem,
    SocialPublication,
    SocialPublicationAsset,
)
from app.models.risk import Risk
from app.models.rbac import Permission, Role, RolePermission, UserRole
from app.models.task import (
    Approval,
    ApprovalStep,
    Task,
    TaskAssignment,
    TaskEvidence,
    TaskUpdate,
)
from app.models.user import User

__all__ = [
    "Base",
    "Organization",
    "Department",
    "Position",
    "Employee",
    "User",
    "Role",
    "Permission",
    "UserRole",
    "RolePermission",
    "Project",
    "Site",
    "ProjectMember",
    "ProjectLocation",
    "Task",
    "TaskAssignment",
    "TaskUpdate",
    "TaskEvidence",
    "Approval",
    "ApprovalStep",
    "File",
    "Document",
    "DocumentVersion",
    "DailyReport",
    "Notification",
    "AIAgent",
    "AgentRun",
    "AgentProposal",
    "AuditEvent",
    "ProjectAccess",
    "SiteWorkerAssignment",
    "WorkShift",
    "PayrollDraft",
    "PayrollLine",
    "SafetyClearance",
    "WorkPermit",
    "ForemanJournal",
    "DailyReportHeadcount",
    "DailyReportIssue",
    "DailyReportEquipment",
    "DailyReportFile",
    "Equipment",
    "EquipmentAssignment",
    "EquipmentUsageLog",
    "EquipmentInspection",
    "MaintenanceOrder",
    "FuelTransaction",
    "Tool",
    "ToolAssignment",
    "InboxItem",
    "Risk",
    "IntegrationConnector",
    "OutboundMessage",
    "ContentPlanItem",
    "SocialPublication",
    "SocialPublicationAsset",
    "AuditFinding",
    "ProjectMilestone",
    "ProjectDiscipline",
    "Counterparty",
    "Supplier",
    "Material",
    "SupplierProduct",
    "DesignBrief",
    "DesignConcept",
    "DesignSpecification",
    "MarketAvailabilityCheck",
    "DesignIssue",
    "Warehouse",
    "WarehouseLocation",
    "ProcurementSettings",
    "MaterialRequest",
    "MaterialRequestLine",
    "RequestForQuotation",
    "RfqLine",
    "RfqSupplier",
    "SupplierItemOffer",
    "PurchaseOrder",
    "PurchaseOrderLine",
    "StockReservation",
    "GoodsReceipt",
    "GoodsReceiptLine",
    "InventoryBalance",
    "InventoryTransaction",
    "MaterialIssue",
    "MaterialIssueLine",
    "StockTransfer",
    "MaterialReturn",
    "WriteOffDocument",
    "InventoryCount",
    "InventoryCountLine",
    "DailyReportWorkItem",
    "UnitOfMeasure",
    "RateItem",
    "PricingSettings",
    "Estimate",
    "EstimatePosition",
    "EstimateChange",
    "CommercialOffer",
    "QuoteComparison",
    "CrmSettings",
    "LeadSource",
    "DealLossReason",
    "PipelineStage",
    "CounterpartyContact",
    "Lead",
    "Deal",
    "DealStageHistory",
    "Communication",
    "Contract",
    "SalesTarget",
    "FinanceSettings",
    "ExpenseCategory",
    "Budget",
    "BudgetLine",
    "FinancialCommitment",
    "Invoice",
    "PaymentRequest",
    "Payment",
    "AccountableAdvance",
    "AccountableExpense",
    "ExpenseDocument",
    "AdvanceReport",
    "AdvanceSettlement",
]
