"""personnel module

Revision ID: 0010_personnel
Revises: 0009_project_access
Create Date: 2026-07-19 10:34:24.112498
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0010_personnel'
down_revision: str | None = '0009_project_access'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foreman_journals',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('journal_type', sa.String(length=32), nullable=False),
    sa.Column('responsible_employee_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('last_filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attachments_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_foreman_journals_organization_id_organizations')),
    sa.ForeignKeyConstraint(['responsible_employee_id'], ['employees.id'], name=op.f('fk_foreman_journals_responsible_employee_id_employees')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_foreman_journals_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foreman_journals'))
    )
    op.create_table('payroll_drafts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_accrued', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_advance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_deduction', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_to_pay', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('risk_level', sa.String(length=2), nullable=False),
    sa.Column('approval_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], name=op.f('fk_payroll_drafts_approval_id_approvals')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_payroll_drafts_organization_id_organizations')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_payroll_drafts_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_drafts'))
    )
    op.create_table('safety_clearances',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('intro_briefing_at', sa.Date(), nullable=True),
    sa.Column('primary_briefing_at', sa.Date(), nullable=True),
    sa.Column('targeted_briefing_at', sa.Date(), nullable=True),
    sa.Column('signed_by_worker', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('medical_valid_until', sa.Date(), nullable=True),
    sa.Column('signature_document_id', sa.Uuid(), nullable=True),
    sa.Column('certificates', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_safety_clearances_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_safety_clearances_organization_id_organizations')),
    sa.ForeignKeyConstraint(['signature_document_id'], ['documents.id'], name=op.f('fk_safety_clearances_signature_document_id_documents')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_safety_clearances_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_safety_clearances'))
    )
    op.create_table('site_worker_assignments',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('brigade', sa.String(length=64), nullable=True),
    sa.Column('profession', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_responsible', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_site_worker_assignments_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_site_worker_assignments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_site_worker_assignments_project_id_projects')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_site_worker_assignments_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_worker_assignments'))
    )
    op.create_table('daily_report_headcount',
    sa.Column('daily_report_id', sa.Uuid(), nullable=False),
    sa.Column('profession', sa.String(length=128), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.id'], name=op.f('fk_daily_report_headcount_daily_report_id_daily_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_report_headcount'))
    )
    op.create_table('daily_report_issues',
    sa.Column('daily_report_id', sa.Uuid(), nullable=False),
    sa.Column('issue_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.id'], name=op.f('fk_daily_report_issues_daily_report_id_daily_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_report_issues'))
    )
    op.create_table('payroll_lines',
    sa.Column('payroll_draft_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('scheme', sa.String(length=16), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('accrued', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('advance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('deduction', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('to_pay', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_payroll_lines_employee_id_employees')),
    sa.ForeignKeyConstraint(['payroll_draft_id'], ['payroll_drafts.id'], name=op.f('fk_payroll_lines_payroll_draft_id_payroll_drafts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_lines'))
    )
    op.create_table('work_permits',
    sa.Column('clearance_id', sa.Uuid(), nullable=False),
    sa.Column('permit_type', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['clearance_id'], ['safety_clearances.id'], name=op.f('fk_work_permits_clearance_id_safety_clearances')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_work_permits_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_permits'))
    )
    op.create_table('work_shifts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('shift_type', sa.String(length=16), nullable=False),
    sa.Column('arrival_time', sa.String(length=5), nullable=True),
    sa.Column('departure_time', sa.String(length=5), nullable=True),
    sa.Column('hours_worked', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('idle_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('absence_type', sa.String(length=32), nullable=True),
    sa.Column('volume_note', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['site_worker_assignments.id'], name=op.f('fk_work_shifts_assignment_id_site_worker_assignments')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_work_shifts_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_work_shifts_organization_id_organizations')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_work_shifts_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_shifts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_shifts')
    op.drop_table('work_permits')
    op.drop_table('payroll_lines')
    op.drop_table('daily_report_issues')
    op.drop_table('daily_report_headcount')
    op.drop_table('site_worker_assignments')
    op.drop_table('safety_clearances')
    op.drop_table('payroll_drafts')
    op.drop_table('foreman_journals')
    # ### end Alembic commands ###
