"""design project workspace

Revision ID: 0011_design
Revises: 0010_personnel
Create Date: 2026-07-19 11:12:32.375109
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0011_design'
down_revision: str | None = '0010_personnel'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparties',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('counterparty_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_counterparties_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counterparties'))
    )
    op.create_table('materials',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('attributes_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_materials_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials'))
    )
    op.create_table('design_briefs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('client_requirements', sa.Text(), nullable=True),
    sa.Column('functional_requirements', sa.Text(), nullable=True),
    sa.Column('style_preferences', sa.Text(), nullable=True),
    sa.Column('budget_range', sa.String(length=128), nullable=True),
    sa.Column('target_completion_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approval_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], name=op.f('fk_design_briefs_approval_id_approvals')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_design_briefs_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_design_briefs_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_design_briefs'))
    )
    op.create_table('project_milestones',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_milestones_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_milestones'))
    )
    op.create_table('suppliers',
    sa.Column('counterparty_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_categories', sa.String(length=255), nullable=True),
    sa.Column('regions', sa.String(length=255), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], name=op.f('fk_suppliers_counterparty_id_counterparties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_table('project_disciplines',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('milestone_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('discipline_type', sa.String(length=32), nullable=False),
    sa.Column('responsible_employee_id', sa.Uuid(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completion_percent', sa.Integer(), nullable=False),
    sa.Column('gip_status', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['project_milestones.id'], name=op.f('fk_project_disciplines_milestone_id_project_milestones')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_disciplines_project_id_projects')),
    sa.ForeignKeyConstraint(['responsible_employee_id'], ['employees.id'], name=op.f('fk_project_disciplines_responsible_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_disciplines'))
    )
    op.create_table('supplier_products',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_sku', sa.String(length=128), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_valid_until', sa.Date(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('minimum_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('availability_status', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('product_url', sa.String(length=1024), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_supplier_products_material_id_materials')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_products_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_products'))
    )
    op.create_table('design_concepts',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('prepared_by', sa.Uuid(), nullable=True),
    sa.Column('presentation_file_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('client_feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['presentation_file_id'], ['files.id'], name=op.f('fk_design_concepts_presentation_file_id_files')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_design_concepts_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_design_concepts'))
    )
    op.create_table('design_issues',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('discipline_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('responsible_employee_id', sa.Uuid(), nullable=True),
    sa.Column('linked_task_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['project_disciplines.id'], name=op.f('fk_design_issues_discipline_id_project_disciplines')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_design_issues_document_id_documents')),
    sa.ForeignKeyConstraint(['linked_task_id'], ['tasks.id'], name=op.f('fk_design_issues_linked_task_id_tasks')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_design_issues_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_design_issues_project_id_projects')),
    sa.ForeignKeyConstraint(['responsible_employee_id'], ['employees.id'], name=op.f('fk_design_issues_responsible_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_design_issues'))
    )
    op.create_table('design_specifications',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_product_id', sa.Uuid(), nullable=True),
    sa.Column('custom_description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('planned_unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('approved_analog_allowed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['design_concepts.id'], name=op.f('fk_design_specifications_concept_id_design_concepts')),
    sa.ForeignKeyConstraint(['location_id'], ['project_locations.id'], name=op.f('fk_design_specifications_location_id_project_locations')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_design_specifications_material_id_materials')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_design_specifications_project_id_projects')),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_products.id'], name=op.f('fk_design_specifications_supplier_product_id_supplier_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_design_specifications'))
    )
    op.create_table('market_availability_checks',
    sa.Column('design_specification_id', sa.Uuid(), nullable=False),
    sa.Column('checked_by_agent_id', sa.Uuid(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('availability_status', sa.String(length=32), nullable=False),
    sa.Column('supplier_count', sa.Integer(), nullable=True),
    sa.Column('minimum_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('maximum_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('regional_delivery_possible', sa.Boolean(), nullable=True),
    sa.Column('recommended_option', sa.String(length=255), nullable=True),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['design_specification_id'], ['design_specifications.id'], name=op.f('fk_market_availability_checks_design_specification_id_design_specifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_availability_checks'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_availability_checks')
    op.drop_table('design_specifications')
    op.drop_table('design_issues')
    op.drop_table('design_concepts')
    op.drop_table('supplier_products')
    op.drop_table('project_disciplines')
    op.drop_table('suppliers')
    op.drop_table('project_milestones')
    op.drop_table('design_briefs')
    op.drop_table('materials')
    op.drop_table('counterparties')
    # ### end Alembic commands ###
