"""crm core

Revision ID: b6ad31369a11
Revises: 0013_procurement
Create Date: 2026-07-19 15:36:44.857036
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0014_crm'
down_revision: str | None = '0013_procurement'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_settings',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('deal_r4_amount_threshold', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_crm_settings_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crm_settings')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_crm_settings_organization_id'))
    )
    op.create_table('deal_loss_reasons',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_deal_loss_reasons_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_loss_reasons'))
    )
    op.create_table('lead_sources',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_lead_sources_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_sources'))
    )
    op.create_table('pipeline_stages',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('probability_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_won', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_lost', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_pipeline_stages_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_stages'))
    )
    op.create_table('counterparty_contacts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('messenger', sa.String(length=128), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('consent_given', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('consent_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], name=op.f('fk_counterparty_contacts_counterparty_id_counterparties')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_counterparty_contacts_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counterparty_contacts'))
    )
    op.create_table('leads',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('lead_source_id', sa.Uuid(), nullable=True),
    sa.Column('counterparty_id', sa.Uuid(), nullable=True),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('estimated_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('responsible_employee_id', sa.Uuid(), nullable=True),
    sa.Column('converted_deal_id', sa.Uuid(), nullable=True),
    sa.Column('qualified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], name=op.f('fk_leads_counterparty_id_counterparties')),
    sa.ForeignKeyConstraint(['lead_source_id'], ['lead_sources.id'], name=op.f('fk_leads_lead_source_id_lead_sources')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_leads_organization_id_organizations')),
    sa.ForeignKeyConstraint(['responsible_employee_id'], ['employees.id'], name=op.f('fk_leads_responsible_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_table('sales_targets',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('target_deals_count', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_sales_targets_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sales_targets_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_targets'))
    )
    op.create_table('deals',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('pipeline_stage_id', sa.Uuid(), nullable=True),
    sa.Column('commercial_offer_id', sa.Uuid(), nullable=True),
    sa.Column('contract_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('risk_level', sa.String(length=2), nullable=False),
    sa.Column('responsible_employee_id', sa.Uuid(), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loss_reason_id', sa.Uuid(), nullable=True),
    sa.Column('loss_comment', sa.String(length=500), nullable=True),
    sa.Column('approval_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], name=op.f('fk_deals_approval_id_approvals')),
    sa.ForeignKeyConstraint(['commercial_offer_id'], ['commercial_offers.id'], name=op.f('fk_deals_commercial_offer_id_commercial_offers')),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], name=op.f('fk_deals_counterparty_id_counterparties')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_deals_lead_id_leads')),
    sa.ForeignKeyConstraint(['loss_reason_id'], ['deal_loss_reasons.id'], name=op.f('fk_deals_loss_reason_id_deal_loss_reasons')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_deals_organization_id_organizations')),
    sa.ForeignKeyConstraint(['pipeline_stage_id'], ['pipeline_stages.id'], name=op.f('fk_deals_pipeline_stage_id_pipeline_stages')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_deals_project_id_projects')),
    sa.ForeignKeyConstraint(['responsible_employee_id'], ['employees.id'], name=op.f('fk_deals_responsible_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals'))
    )
    op.create_table('communications',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('classification', sa.String(length=64), nullable=True),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('responsible_employee_id', sa.Uuid(), nullable=True),
    sa.Column('linked_task_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['counterparty_contacts.id'], name=op.f('fk_communications_contact_id_counterparty_contacts')),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], name=op.f('fk_communications_counterparty_id_counterparties')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_communications_deal_id_deals')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_communications_lead_id_leads')),
    sa.ForeignKeyConstraint(['linked_task_id'], ['tasks.id'], name=op.f('fk_communications_linked_task_id_tasks')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_communications_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_communications_project_id_projects')),
    sa.ForeignKeyConstraint(['responsible_employee_id'], ['employees.id'], name=op.f('fk_communications_responsible_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communications'))
    )
    op.create_table('contracts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('commercial_offer_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('contract_type', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=128), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('signed_at', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk_level', sa.String(length=2), nullable=False),
    sa.Column('responsible_employee_id', sa.Uuid(), nullable=True),
    sa.Column('approval_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], name=op.f('fk_contracts_approval_id_approvals')),
    sa.ForeignKeyConstraint(['commercial_offer_id'], ['commercial_offers.id'], name=op.f('fk_contracts_commercial_offer_id_commercial_offers')),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], name=op.f('fk_contracts_counterparty_id_counterparties')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_contracts_deal_id_deals')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_contracts_document_id_documents')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_contracts_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_contracts_project_id_projects')),
    sa.ForeignKeyConstraint(['responsible_employee_id'], ['employees.id'], name=op.f('fk_contracts_responsible_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts'))
    )
    op.create_table('deal_stage_history',
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('from_stage_id', sa.Uuid(), nullable=True),
    sa.Column('to_stage_id', sa.Uuid(), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_deal_stage_history_deal_id_deals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_stage_history'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_projects_customer_id_counterparties'), 'counterparties', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_projects_customer_id_counterparties'), type_='foreignkey')

    op.drop_table('deal_stage_history')
    op.drop_table('contracts')
    op.drop_table('communications')
    op.drop_table('deals')
    op.drop_table('sales_targets')
    op.drop_table('leads')
    op.drop_table('counterparty_contacts')
    op.drop_table('pipeline_stages')
    op.drop_table('lead_sources')
    op.drop_table('deal_loss_reasons')
    op.drop_table('crm_settings')
    # ### end Alembic commands ###
