"""accountable funds

Revision ID: 48cd87894d84
Revises: 0016_finance_pay
Create Date: 2026-07-19 18:54:07.242194
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0017_accountable'
down_revision: str | None = '0016_finance_pay'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountable_advances',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('expense_category_id', sa.Uuid(), nullable=True),
    sa.Column('advance_number', sa.String(length=64), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('amount_issued', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('issued_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approval_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('amount_spent_confirmed', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_returned', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_reimbursable', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=2), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], name=op.f('fk_accountable_advances_approval_id_approvals')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_accountable_advances_employee_id_employees')),
    sa.ForeignKeyConstraint(['expense_category_id'], ['expense_categories.id'], name=op.f('fk_accountable_advances_expense_category_id_expense_categories')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_accountable_advances_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_accountable_advances_project_id_projects')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_accountable_advances_site_id_sites')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_accountable_advances_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accountable_advances'))
    )
    op.create_table('accountable_expenses',
    sa.Column('advance_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('expense_category_id', sa.Uuid(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('receipt_required', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('document_status', sa.String(length=20), nullable=False),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('verified_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_from_mobile', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['advance_id'], ['accountable_advances.id'], name=op.f('fk_accountable_expenses_advance_id_accountable_advances')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_accountable_expenses_employee_id_employees')),
    sa.ForeignKeyConstraint(['expense_category_id'], ['expense_categories.id'], name=op.f('fk_accountable_expenses_expense_category_id_expense_categories')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_accountable_expenses_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_accountable_expenses_project_id_projects')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_accountable_expenses_site_id_sites')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_accountable_expenses_supplier_id_suppliers')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_accountable_expenses_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accountable_expenses'))
    )
    op.create_table('advance_reports',
    sa.Column('advance_id', sa.Uuid(), nullable=False),
    sa.Column('report_number', sa.String(length=64), nullable=True),
    sa.Column('submitted_by_employee_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('total_expenses_submitted', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_expenses_approved', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_to_return', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_to_reimburse', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('accountant_user_id', sa.Uuid(), nullable=True),
    sa.Column('accountant_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accounting_export_status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['advance_id'], ['accountable_advances.id'], name=op.f('fk_advance_reports_advance_id_accountable_advances')),
    sa.ForeignKeyConstraint(['submitted_by_employee_id'], ['employees.id'], name=op.f('fk_advance_reports_submitted_by_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advance_reports'))
    )
    op.create_table('advance_settlements',
    sa.Column('advance_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('settlement_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('processed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['advance_id'], ['accountable_advances.id'], name=op.f('fk_advance_settlements_advance_id_accountable_advances')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_advance_settlements_file_id_files')),
    sa.ForeignKeyConstraint(['report_id'], ['advance_reports.id'], name=op.f('fk_advance_settlements_report_id_advance_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advance_settlements')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_advance_settlements_idempotency_key'))
    )
    op.create_table('expense_documents',
    sa.Column('expense_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('document_number', sa.String(length=128), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('seller_name', sa.String(length=255), nullable=True),
    sa.Column('seller_tax_id', sa.String(length=32), nullable=True),
    sa.Column('fiscal_sign', sa.String(length=64), nullable=True),
    sa.Column('extracted_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('extracted_currency', sa.String(length=3), nullable=True),
    sa.Column('ocr_status', sa.String(length=16), nullable=False),
    sa.Column('duplicate_hash', sa.String(length=128), nullable=True),
    sa.Column('validated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['accountable_expenses.id'], name=op.f('fk_expense_documents_expense_id_accountable_expenses')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_expense_documents_file_id_files')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_expense_documents_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_documents')),
    sa.UniqueConstraint('duplicate_hash', name=op.f('uq_expense_documents_duplicate_hash'))
    )
    with op.batch_alter_table('expense_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_project', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('requires_site', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('requires_receipt', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('requires_preapproval', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('default_limit', sa.Numeric(precision=18, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_categories', schema=None) as batch_op:
        batch_op.drop_column('default_limit')
        batch_op.drop_column('requires_preapproval')
        batch_op.drop_column('requires_receipt')
        batch_op.drop_column('requires_site')
        batch_op.drop_column('requires_project')

    op.drop_table('expense_documents')
    op.drop_table('advance_settlements')
    op.drop_table('advance_reports')
    op.drop_table('accountable_expenses')
    op.drop_table('accountable_advances')
    # ### end Alembic commands ###
