"""material request issue lifecycle

Revision ID: bd05a2242c26
Revises: 0017_accountable
Create Date: 2026-07-19 19:33:16.596429
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0018_material_flow'
down_revision: str | None = '0017_accountable'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_issue_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_request_line_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_material_issue_lines_material_request_line_id_material_request_lines'), 'material_request_lines', ['material_request_line_id'], ['id'])

    with op.batch_alter_table('material_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_request_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('issued_by', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('acknowledgement_status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False))
        batch_op.add_column(sa.Column('acknowledged_by', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('dispute_reason', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('evidence_document_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('evidence_file_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_material_issues_evidence_file_id_files'), 'files', ['evidence_file_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_material_issues_issued_by_employees'), 'employees', ['issued_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_material_issues_evidence_document_id_documents'), 'documents', ['evidence_document_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_material_issues_material_request_id_material_requests'), 'material_requests', ['material_request_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_material_issues_acknowledged_by_employees'), 'employees', ['acknowledged_by'], ['id'])

    with op.batch_alter_table('material_request_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('issued_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('returned_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('material_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('responsible_employee_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('is_critical', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('risk_level', sa.String(length=2), server_default=sa.text("'R0'"), nullable=False))
        batch_op.add_column(sa.Column('decided_by_user_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_material_requests_task_id_tasks'), 'tasks', ['task_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_material_requests_responsible_employee_id_employees'), 'employees', ['responsible_employee_id'], ['id'])

    with op.batch_alter_table('material_returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_request_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('material_issue_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_by', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('evidence_document_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_material_returns_material_issue_id_material_issues'), 'material_issues', ['material_issue_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_material_returns_material_request_id_material_requests'), 'material_requests', ['material_request_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_material_returns_evidence_document_id_documents'), 'documents', ['evidence_document_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_material_returns_confirmed_by_employees'), 'employees', ['confirmed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_returns', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_material_returns_confirmed_by_employees'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_material_returns_evidence_document_id_documents'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_material_returns_material_request_id_material_requests'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_material_returns_material_issue_id_material_issues'), type_='foreignkey')
        batch_op.drop_column('evidence_document_id')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('confirmed_by')
        batch_op.drop_column('material_issue_id')
        batch_op.drop_column('material_request_id')

    with op.batch_alter_table('material_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_material_requests_responsible_employee_id_employees'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_material_requests_task_id_tasks'), type_='foreignkey')
        batch_op.drop_column('closed_at')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('decided_at')
        batch_op.drop_column('decided_by_user_id')
        batch_op.drop_column('risk_level')
        batch_op.drop_column('is_critical')
        batch_op.drop_column('responsible_employee_id')
        batch_op.drop_column('task_id')

    with op.batch_alter_table('material_request_lines', schema=None) as batch_op:
        batch_op.drop_column('returned_quantity')
        batch_op.drop_column('issued_quantity')
        batch_op.drop_column('reserved_quantity')

    with op.batch_alter_table('material_issues', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_material_issues_acknowledged_by_employees'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_material_issues_material_request_id_material_requests'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_material_issues_evidence_document_id_documents'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_material_issues_issued_by_employees'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_material_issues_evidence_file_id_files'), type_='foreignkey')
        batch_op.drop_column('evidence_file_id')
        batch_op.drop_column('evidence_document_id')
        batch_op.drop_column('dispute_reason')
        batch_op.drop_column('acknowledged_at')
        batch_op.drop_column('acknowledged_by')
        batch_op.drop_column('acknowledgement_status')
        batch_op.drop_column('issued_by')
        batch_op.drop_column('material_request_id')

    with op.batch_alter_table('material_issue_lines', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_material_issue_lines_material_request_line_id_material_request_lines'), type_='foreignkey')
        batch_op.drop_column('material_request_line_id')

    # ### end Alembic commands ###
