"""inventory stock ledger

Revision ID: dc0a7c6d7b6c
Revises: 0018_material_flow
Create Date: 2026-07-19 19:59:53.096168
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0019_inventory_ledger'
down_revision: str | None = '0018_material_flow'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minimum_quantity', sa.Numeric(precision=16, scale=3), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('stock_reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved_by_user_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('reserved_until', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('released_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_reservations', schema=None) as batch_op:
        batch_op.drop_column('released_at')
        batch_op.drop_column('reason')
        batch_op.drop_column('reserved_until')
        batch_op.drop_column('reserved_by_user_id')

    with op.batch_alter_table('inventory_balances', schema=None) as batch_op:
        batch_op.drop_column('minimum_quantity')

    # ### end Alembic commands ###
