"""field report equipment evidence

Revision ID: d769644e141c
Revises: 0019_inventory_ledger
Create Date: 2026-07-19 20:19:27.454968
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0020_field_report'
down_revision: str | None = '0019_inventory_ledger'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_report_equipment',
    sa.Column('daily_report_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('equipment_type', sa.String(length=64), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.id'], name=op.f('fk_daily_report_equipment_daily_report_id_daily_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_report_equipment'))
    )
    op.create_table('daily_report_files',
    sa.Column('daily_report_id', sa.Uuid(), nullable=False),
    sa.Column('work_item_id', sa.Uuid(), nullable=True),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.id'], name=op.f('fk_daily_report_files_daily_report_id_daily_reports')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_daily_report_files_file_id_files')),
    sa.ForeignKeyConstraint(['work_item_id'], ['daily_report_work_items.id'], name=op.f('fk_daily_report_files_work_item_id_daily_report_work_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_report_files'))
    )
    with op.batch_alter_table('daily_report_work_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_daily_report_work_items_task_id_tasks'), 'tasks', ['task_id'], ['id'])

    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('review_comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_column('review_comment')
        batch_op.drop_column('reviewed_by_user_id')

    with op.batch_alter_table('daily_report_work_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_daily_report_work_items_task_id_tasks'), type_='foreignkey')
        batch_op.drop_column('task_id')

    op.drop_table('daily_report_files')
    op.drop_table('daily_report_equipment')
    # ### end Alembic commands ###
