"""task execution control fields

Revision ID: a34a2d6f76fe
Revises: 0020_field_report
Create Date: 2026-07-19 20:39:19.021726
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0021_task_control'
down_revision: str | None = '0020_field_report'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocked_reason', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('escalation_level', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('escalated_at')
        batch_op.drop_column('escalation_level')
        batch_op.drop_column('blocked_reason')

    # ### end Alembic commands ###
