"""smm publications (этап 17): контент-план, публикации-черновики, материалы

Revision ID: 0027_smm
Revises: 0026_integrations
Create Date: 2026-07-19
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0027_smm'
down_revision: str | None = '0026_integrations'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_plan_items',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('theme', sa.String(length=128), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_content_plan_items_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_content_plan_items_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_plan_items'))
    )
    op.create_table('social_publications',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('plan_item_id', sa.Uuid(), nullable=True),
    sa.Column('connector_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rights_confirmed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('pii_checked', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('legal_checked', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_level', sa.String(length=2), nullable=False),
    sa.Column('approval_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], name=op.f('fk_social_publications_approval_id_approvals')),
    sa.ForeignKeyConstraint(['connector_id'], ['integration_connectors.id'], name=op.f('fk_social_publications_connector_id_integration_connectors')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_social_publications_organization_id_organizations')),
    sa.ForeignKeyConstraint(['plan_item_id'], ['content_plan_items.id'], name=op.f('fk_social_publications_plan_item_id_content_plan_items')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_social_publications_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_publications'))
    )
    op.create_table('social_publication_assets',
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('quality_ok', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('rights_ok', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_social_publication_assets_file_id_files')),
    sa.ForeignKeyConstraint(['publication_id'], ['social_publications.id'], name=op.f('fk_social_publication_assets_publication_id_social_publications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_publication_assets'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_publication_assets')
    op.drop_table('social_publications')
    op.drop_table('content_plan_items')
    # ### end Alembic commands ###
