"""executive documents

Revision ID: 0029_executive_documents
Revises: 0028_audit_findings
Create Date: 2026-07-20 00:08:35.434569
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0029_executive_documents'
down_revision: str | None = '0028_audit_findings'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executive_documents',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('work_item_type', sa.String(length=32), nullable=True),
    sa.Column('work_item_id', sa.Uuid(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approval_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], name=op.f('fk_executive_documents_approval_id_approvals')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_executive_documents_file_id_files')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_executive_documents_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_executive_documents_project_id_projects')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['executive_documents.id'], name=op.f('fk_executive_documents_supersedes_id_executive_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executive_documents'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('executive_documents')
    # ### end Alembic commands ###
