"""daily report client_request_id

Revision ID: 0030_daily_report_idempotency
Revises: 0029_executive_documents
Create Date: 2026-07-20 09:31:49.876188
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0030_daily_report_idempotency'
down_revision: str | None = '0029_executive_documents'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_request_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_daily_reports_client_request_id'), ['client_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_reports_client_request_id'))
        batch_op.drop_column('client_request_id')

    # ### end Alembic commands ###
