"""audit hardening fields

Revision ID: 0033_audit_hardening_fields
Revises: 0032_user_role_authority_period
Create Date: 2026-07-22 09:28:32.778751
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0033_audit_hardening_fields'
down_revision: str | None = '0032_user_role_authority_period'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_position_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('auth_level', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_events_actor_user_id'), ['actor_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_user_id'))
        batch_op.drop_column('auth_level')
        batch_op.drop_column('session_id')
        batch_op.drop_column('actor_position_id')

    # ### end Alembic commands ###
