"""document integrity lock

Revision ID: 0034_document_integrity_lock
Revises: 0033_audit_hardening_fields
Create Date: 2026-07-22 16:39:42.554841
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0034_document_integrity_lock'
down_revision: str | None = '0033_audit_hardening_fields'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('locked_by', sa.Uuid(), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('locked_by', sa.Uuid(), nullable=True))

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('locked_by', sa.Uuid(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('locked_by')
        batch_op.drop_column('locked_at')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('locked_by')
        batch_op.drop_column('locked_at')

    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_column('locked_by')
        batch_op.drop_column('locked_at')
        batch_op.drop_column('approved_at')

    # ### end Alembic commands ###
