"""normative registry and project profile

Revision ID: 0035_normative_registry
Revises: 0034_document_integrity_lock
Create Date: 2026-07-22 19:08:47.087070
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0035_normative_registry'
down_revision: str | None = '0034_document_integrity_lock'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('normative_documents',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('full_title', sa.String(length=1024), nullable=False),
    sa.Column('number', sa.String(length=128), nullable=True),
    sa.Column('doc_kind', sa.String(length=32), nullable=False),
    sa.Column('edition', sa.String(length=128), nullable=True),
    sa.Column('amendment_no', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('official_source_url', sa.String(length=1024), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('work_types', sa.JSON(), nullable=True),
    sa.Column('object_types', sa.JSON(), nullable=True),
    sa.Column('related_control_ops', sa.JSON(), nullable=True),
    sa.Column('responsible_user_id', sa.Uuid(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_normative_documents_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_normative_documents'))
    )
    with op.batch_alter_table('normative_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_normative_documents_organization_id'), ['organization_id'], unique=False)

    op.create_table('project_normative_profiles',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_project_normative_profiles_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_normative_profiles_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_normative_profiles')),
    sa.UniqueConstraint('project_id', name=op.f('uq_project_normative_profiles_project_id'))
    )
    with op.batch_alter_table('project_normative_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_normative_profiles_organization_id'), ['organization_id'], unique=False)

    op.create_table('project_normative_items',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('normative_document_id', sa.Uuid(), nullable=False),
    sa.Column('applicable_edition', sa.String(length=128), nullable=True),
    sa.Column('mandatory', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('work_types', sa.JSON(), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['normative_document_id'], ['normative_documents.id'], name=op.f('fk_project_normative_items_normative_document_id_normative_documents')),
    sa.ForeignKeyConstraint(['profile_id'], ['project_normative_profiles.id'], name=op.f('fk_project_normative_items_profile_id_project_normative_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_normative_items')),
    sa.UniqueConstraint('profile_id', 'normative_document_id', name=op.f('uq_project_normative_items_profile_id'))
    )
    with op.batch_alter_table('project_normative_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_normative_items_profile_id'), ['profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_normative_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_normative_items_profile_id'))

    op.drop_table('project_normative_items')
    with op.batch_alter_table('project_normative_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_normative_profiles_organization_id'))

    op.drop_table('project_normative_profiles')
    with op.batch_alter_table('normative_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_normative_documents_organization_id'))

    op.drop_table('normative_documents')
    # ### end Alembic commands ###
