"""workflow processes core

Revision ID: 0037_workflow_processes_core
Revises: 0036_webauthn_credentials
Create Date: 2026-07-22 20:09:02.459563
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0037_workflow_processes_core'
down_revision: str | None = '0036_webauthn_credentials'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_processes',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('process_kind', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=2), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('executor_comment', sa.Text(), nullable=True),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('initiator_user_id', sa.Uuid(), nullable=True),
    sa.Column('responsible_manager_id', sa.Uuid(), nullable=True),
    sa.Column('primary_executor_id', sa.Uuid(), nullable=True),
    sa.Column('co_executor_ids', sa.JSON(), nullable=True),
    sa.Column('watcher_ids', sa.JSON(), nullable=True),
    sa.Column('start_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reschedule_count', sa.Integer(), nullable=False),
    sa.Column('related_document_ids', sa.JSON(), nullable=True),
    sa.Column('related_material_ids', sa.JSON(), nullable=True),
    sa.Column('source_kind', sa.String(length=48), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_workflow_processes_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_workflow_processes_project_id_projects')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_workflow_processes_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_processes'))
    )
    with op.batch_alter_table('workflow_processes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_processes_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_processes_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_processes_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_processes_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_processes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_processes_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_processes_project_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_processes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_processes_due_at'))

    op.drop_table('workflow_processes')
    # ### end Alembic commands ###
