"""evidence gate

Revision ID: 0038_evidence_gate
Revises: 0037_workflow_processes_core
Create Date: 2026-07-22 20:31:25.231230
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0038_evidence_gate'
down_revision: str | None = '0037_workflow_processes_core'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_requirement_matrix',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('process_kind', sa.String(length=48), nullable=False),
    sa.Column('evidence_type', sa.String(length=48), nullable=False),
    sa.Column('required', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('condition', sa.String(length=512), nullable=True),
    sa.Column('min_count', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_evidence_requirement_matrix_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_requirement_matrix')),
    sa.UniqueConstraint('organization_id', 'process_kind', 'evidence_type', name=op.f('uq_evidence_requirement_matrix_organization_id'))
    )
    with op.batch_alter_table('evidence_requirement_matrix', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_requirement_matrix_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_requirement_matrix_process_kind'), ['process_kind'], unique=False)

    op.create_table('evidence_exception_requests',
    sa.Column('process_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=48), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['workflow_processes.id'], name=op.f('fk_evidence_exception_requests_process_id_workflow_processes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_exception_requests'))
    )
    with op.batch_alter_table('evidence_exception_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_exception_requests_process_id'), ['process_id'], unique=False)

    op.create_table('process_evidence',
    sa.Column('process_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=48), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('captured_phase', sa.String(length=8), nullable=True),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_process_evidence_file_id_files')),
    sa.ForeignKeyConstraint(['process_id'], ['workflow_processes.id'], name=op.f('fk_process_evidence_process_id_workflow_processes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_process_evidence'))
    )
    with op.batch_alter_table('process_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_evidence_process_id'), ['process_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_evidence_process_id'))

    op.drop_table('process_evidence')
    with op.batch_alter_table('evidence_exception_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_exception_requests_process_id'))

    op.drop_table('evidence_exception_requests')
    with op.batch_alter_table('evidence_requirement_matrix', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_requirement_matrix_process_kind'))
        batch_op.drop_index(batch_op.f('ix_evidence_requirement_matrix_organization_id'))

    op.drop_table('evidence_requirement_matrix')
    # ### end Alembic commands ###
