"""daily report no work

Revision ID: 0039_daily_report_no_work
Revises: 0038_evidence_gate
Create Date: 2026-07-22 20:56:11.628734
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0039_daily_report_no_work'
down_revision: str | None = '0038_evidence_gate'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_work', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('no_work_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_column('no_work_reason')
        batch_op.drop_column('no_work')

    # ### end Alembic commands ###
