"""quality control cards

Revision ID: 0040_quality_control_cards
Revises: 0039_daily_report_no_work
Create Date: 2026-07-22 21:25:47.600936
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0040_quality_control_cards'
down_revision: str | None = '0039_daily_report_no_work'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_control_cards',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('work_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('control_kind', sa.String(length=24), nullable=False),
    sa.Column('normative_item_id', sa.Uuid(), nullable=True),
    sa.Column('controlled_parameter', sa.String(length=512), nullable=False),
    sa.Column('allowed_value', sa.String(length=512), nullable=True),
    sa.Column('check_method', sa.String(length=512), nullable=True),
    sa.Column('responsible_position', sa.String(length=64), nullable=True),
    sa.Column('requires_document', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('requires_photo', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('requires_measurement', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_quality_control_cards_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_quality_control_cards_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_control_cards'))
    )
    with op.batch_alter_table('quality_control_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_control_cards_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_control_cards_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_control_cards_work_type'), ['work_type'], unique=False)

    op.create_table('quality_control_checks',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('process_id', sa.Uuid(), nullable=True),
    sa.Column('checked_by', sa.Uuid(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('measured_value', sa.String(length=512), nullable=True),
    sa.Column('instrument', sa.String(length=255), nullable=True),
    sa.Column('instrument_verification', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('defect_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recheck_required', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('recheck_of_check_id', sa.Uuid(), nullable=True),
    sa.Column('ai_suggestion', sa.Text(), nullable=True),
    sa.Column('final_decision', sa.String(length=16), nullable=True),
    sa.Column('final_decision_by', sa.Uuid(), nullable=True),
    sa.Column('final_decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['quality_control_cards.id'], name=op.f('fk_quality_control_checks_card_id_quality_control_cards')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_quality_control_checks_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_control_checks'))
    )
    with op.batch_alter_table('quality_control_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_control_checks_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_control_checks_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_control_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_control_checks_organization_id'))
        batch_op.drop_index(batch_op.f('ix_quality_control_checks_card_id'))

    op.drop_table('quality_control_checks')
    with op.batch_alter_table('quality_control_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_control_cards_work_type'))
        batch_op.drop_index(batch_op.f('ix_quality_control_cards_project_id'))
        batch_op.drop_index(batch_op.f('ix_quality_control_cards_organization_id'))

    op.drop_table('quality_control_cards')
    # ### end Alembic commands ###
