"""risk thresholds

Revision ID: 0041_risk_thresholds
Revises: 0040_quality_control_cards
Create Date: 2026-07-22 21:37:28.089205
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0041_risk_thresholds'
down_revision: str | None = '0040_quality_control_cards'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_thresholds',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('process_kind', sa.String(length=48), nullable=True),
    sa.Column('metric', sa.String(length=24), nullable=False),
    sa.Column('min_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=2), nullable=False),
    sa.Column('required_approvals', sa.Integer(), nullable=False),
    sa.Column('requires_mfa', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_risk_thresholds_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_risk_thresholds_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_thresholds'))
    )
    with op.batch_alter_table('risk_thresholds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_thresholds_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_thresholds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_thresholds_organization_id'))

    op.drop_table('risk_thresholds')
    # ### end Alembic commands ###
