"""attachments

Revision ID: 0042_attachments
Revises: 0041_risk_thresholds
Create Date: 2026-07-23 19:52:06.480646
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0042_attachments'
down_revision: str | None = '0041_risk_thresholds'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('attachment_type', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('replaces_id', sa.Uuid(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by', sa.Uuid(), nullable=True),
    sa.Column('archive_reason', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_attachments_file_id_files')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_attachments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_attachments_project_id_projects')),
    sa.ForeignKeyConstraint(['replaces_id'], ['attachments.id'], name=op.f('fk_attachments_replaces_id_attachments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('ix_attachments_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_project_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_file_id'))
        batch_op.drop_index('ix_attachments_entity')

    op.drop_table('attachments')
    # ### end Alembic commands ###
