"""communications

Revision ID: 0043_communications
Revises: 0042_attachments
Create Date: 2026-07-23 20:15:37.015403
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0043_communications'
down_revision: str | None = '0042_attachments'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_templates',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_message_templates_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_templates'))
    )
    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_templates_organization_id'), ['organization_id'], unique=False)

    op.create_table('communication_contacts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('telegram', sa.String(length=128), nullable=True),
    sa.Column('whatsapp', sa.String(length=64), nullable=True),
    sa.Column('instagram', sa.String(length=128), nullable=True),
    sa.Column('counterparty_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('consent', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('stop_listed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_communication_contacts_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_communication_contacts_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communication_contacts'))
    )
    with op.batch_alter_table('communication_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communication_contacts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_contacts_project_id'), ['project_id'], unique=False)

    op.create_table('communication_messages',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('responsible_user_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('error_reason', sa.String(length=512), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('broadcast_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['integration_connectors.id'], name=op.f('fk_communication_messages_connector_id_integration_connectors')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_communication_messages_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_communication_messages_project_id_projects')),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], name=op.f('fk_communication_messages_template_id_message_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communication_messages'))
    )
    with op.batch_alter_table('communication_messages', schema=None) as batch_op:
        batch_op.create_index('ix_comm_messages_dir_status', ['direction', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_messages_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_messages_project_id'), ['project_id'], unique=False)

    op.create_table('message_recipients',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('error_reason', sa.String(length=512), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['communication_contacts.id'], name=op.f('fk_message_recipients_contact_id_communication_contacts')),
    sa.ForeignKeyConstraint(['message_id'], ['communication_messages.id'], name=op.f('fk_message_recipients_message_id_communication_messages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_recipients'))
    )
    with op.batch_alter_table('message_recipients', schema=None) as batch_op:
        batch_op.create_index('ix_message_recipients_message', ['message_id'], unique=False)

    op.create_table('message_delivery_events',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=True),
    sa.Column('event', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['communication_messages.id'], name=op.f('fk_message_delivery_events_message_id_communication_messages')),
    sa.ForeignKeyConstraint(['recipient_id'], ['message_recipients.id'], name=op.f('fk_message_delivery_events_recipient_id_message_recipients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_delivery_events'))
    )
    with op.batch_alter_table('message_delivery_events', schema=None) as batch_op:
        batch_op.create_index('ix_delivery_events_message', ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_delivery_events', schema=None) as batch_op:
        batch_op.drop_index('ix_delivery_events_message')

    op.drop_table('message_delivery_events')
    with op.batch_alter_table('message_recipients', schema=None) as batch_op:
        batch_op.drop_index('ix_message_recipients_message')

    op.drop_table('message_recipients')
    with op.batch_alter_table('communication_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communication_messages_project_id'))
        batch_op.drop_index(batch_op.f('ix_communication_messages_organization_id'))
        batch_op.drop_index('ix_comm_messages_dir_status')

    op.drop_table('communication_messages')
    with op.batch_alter_table('communication_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communication_contacts_project_id'))
        batch_op.drop_index(batch_op.f('ix_communication_contacts_organization_id'))

    op.drop_table('communication_contacts')
    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_templates_organization_id'))

    op.drop_table('message_templates')
    # ### end Alembic commands ###
