"""broadcasts

Revision ID: 0044_broadcasts
Revises: 0043_communications
Create Date: 2026-07-23 21:35:52.836703
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0044_broadcasts'
down_revision: str | None = '0043_communications'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_recipient', sa.String(length=255), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_broadcasts_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_broadcasts_project_id_projects')),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], name=op.f('fk_broadcasts_template_id_message_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcasts'))
    )
    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broadcasts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_broadcasts_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('communication_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unsubscribed', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communication_contacts', schema=None) as batch_op:
        batch_op.drop_column('unsubscribed')

    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broadcasts_project_id'))
        batch_op.drop_index(batch_op.f('ix_broadcasts_organization_id'))

    op.drop_table('broadcasts')
    # ### end Alembic commands ###
