"""ai provider layer

Revision ID: 0045_ai_provider_layer
Revises: 0044_broadcasts
Create Date: 2026-07-23 21:54:03.835547
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0045_ai_provider_layer'
down_revision: str | None = '0044_broadcasts'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('default_model', sa.String(length=128), nullable=True),
    sa.Column('credentials_configured_externally', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_providers_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_providers'))
    )
    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_providers_organization_id'), ['organization_id'], unique=False)

    op.create_table('agent_ai_assignments',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('primary_provider_id', sa.Uuid(), nullable=True),
    sa.Column('primary_model', sa.String(length=128), nullable=True),
    sa.Column('fallback_provider_id', sa.Uuid(), nullable=True),
    sa.Column('fallback_model', sa.String(length=128), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('reasoning_level', sa.String(length=16), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('monthly_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('allow_images', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('allow_documents', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('allow_tools', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.id'], name=op.f('fk_agent_ai_assignments_agent_id_ai_agents')),
    sa.ForeignKeyConstraint(['fallback_provider_id'], ['ai_providers.id'], name=op.f('fk_agent_ai_assignments_fallback_provider_id_ai_providers')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_agent_ai_assignments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['primary_provider_id'], ['ai_providers.id'], name=op.f('fk_agent_ai_assignments_primary_provider_id_ai_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_ai_assignments'))
    )
    with op.batch_alter_table('agent_ai_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_ai_assignments_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_ai_assignments_organization_id'), ['organization_id'], unique=False)

    op.create_table('ai_models',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('supports_images', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('supports_tools', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], name=op.f('fk_ai_models_provider_id_ai_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_models'))
    )
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_models_provider_id'), ['provider_id'], unique=False)

    op.create_table('ai_provider_health',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], name=op.f('fk_ai_provider_health_provider_id_ai_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_provider_health'))
    )
    with op.batch_alter_table('ai_provider_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_provider_health_provider_id'), ['provider_id'], unique=False)

    op.create_table('ai_usage_records',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.id'], name=op.f('fk_ai_usage_records_agent_id_ai_agents')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_usage_records_organization_id_organizations')),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], name=op.f('fk_ai_usage_records_provider_id_ai_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage_records'))
    )
    with op.batch_alter_table('ai_usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_records_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_records_organization_id'))

    op.drop_table('ai_usage_records')
    with op.batch_alter_table('ai_provider_health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_provider_health_provider_id'))

    op.drop_table('ai_provider_health')
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_models_provider_id'))

    op.drop_table('ai_models')
    with op.batch_alter_table('agent_ai_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_ai_assignments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_agent_ai_assignments_agent_id'))

    op.drop_table('agent_ai_assignments')
    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_providers_organization_id'))

    op.drop_table('ai_providers')
    # ### end Alembic commands ###
